name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: poketwo
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          image_name: http-proxy
          image_tag: latest,${{ github.sha }}
          build_extra_args: --build-arg FEATURES=expose-metrics
